"""The REPLAN_REEXECUTE transaction: typed durable state and pure verifiers.

REPLAN_REEXECUTE is the only phase in which the controller performs a
*destructive* GitHub write on work an agent produced: it closes the PR that
holds the accumulated review findings and activates a replacement in its
place. Nothing about that write is recoverable by re-running it, so the phase
is modelled as one explicit transaction rather than as a sequence of
independent checks.

Everything here is pure. GitHub I/O and state persistence live in the engine;
this module owns the *decisions*, so the normal path and the crash-recovery
path cannot drift apart by construction — they call the same predicates on
the same persisted intent.

Lifecycle (monotonic; ``REJECTED`` is terminal)::

    PENDING ──► PREPARED ──► VERIFIED ──► SUPERSEDE_INTENT ──► SUPERSEDED ──► (activated)
        │           │             │                │                │
        │           │             │                ▼                │
        │           │             │          COMPENSATING           │
        │           │             │                │                │
        └───────────┴─────────────┴────────────────┴────────────────┴──► REJECTED

``COMPENSATING`` is entered when the close landed on facts that had already
moved; it is persisted *before* the reopen, so a crash after a successful
reopen resumes into "finish undoing", never into "close again".

``PREPARED`` is written *before* the agent is invoked, and carries the
transaction id. Because that id cannot exist anywhere before it is persisted,
"crashed before invoking the agent" and "crashed while the agent ran" are the
same recoverable state: either a PR carrying the id exists, or none does.

Causal provenance
-----------------
A replacement belongs to a transaction only if its PR body carries the
controller-generated marker for *that* transaction id:

.. code-block:: text

    <!-- autoforge-replan-transaction: {"transaction_id": "...", ...} -->

The id is random, generated by the controller, persisted before invocation,
handed to the agent as prompt data, and read back from GitHub. Shape alone
("an open PR linked to the issue", "the only other PR") is never proof:
:func:`select_bound_candidate` ignores every unmarked PR and every PR that
already existed when the transaction was prepared. The marker is also
re-checked on the last read before the destructive write
(:func:`verify_target_marker`), because a body can be edited after the
controller verified it.

The same marker carries the agent's *attestation* — how many historical
findings it accounted for, and whether its own tests passed. Putting the
attestation on GitHub rather than only in the CONTROL_RESULT is what lets
recovery enforce exactly the same acceptance rules as the normal path: after
a crash there is no CONTROL_RESULT to consult, but the marker is still there.
"""

from __future__ import annotations

import json
import re
import secrets
from collections.abc import Iterable
from dataclasses import asdict, dataclass, field
from enum import StrEnum

from .github import PRInfo
from .validation import parse_issue_url, parse_pr_url

MARKER_NAME = "autoforge-replan-transaction"
# Matches *every* complete comment bearing this name, whatever the payload
# looks like -- the payload is then classified, and anything that is not a
# usable attestation is reported as malformed rather than passed over. A
# pattern that only recognised well-formed payloads would silently downgrade
# "this PR carries a broken attestation" (a conclusive refusal) to "this PR
# carries no attestation", which is exactly the ambiguity the phase must fail
# closed on. The payload is therefore *any* text, angle brackets included.
#
# The one thing it may not contain is a comment delimiter. Tempering it with
# `(?!-->|<!--)` stops a marker whose own `-->` is missing from swallowing the
# body up to some later `-->` and hiding a valid marker inside the match: an
# unterminated marker is not a complete comment and is evidence of nothing,
# while every complete one is classified.
MARKER_RE = re.compile(
    rf"<!--\s*{MARKER_NAME}\s*:\s*(?P<payload>(?:(?!-->|<!--)[\s\S])*?)\s*-->"
)

# The controller's receipt for its own destructive close, posted with a
# separate `gh pr comment` after the close is observed (see
# :func:`render_close_receipt`) -- never inside `gh pr close --comment`,
# whose comment predates the close.
CLOSE_RECEIPT_NAME = "autoforge-replan-close"
CLOSE_RECEIPT_RE = re.compile(
    rf"<!--\s*{CLOSE_RECEIPT_NAME}\s*:\s*(?P<txn>[0-9a-f]{{32}})\s*-->"
)

TRANSACTION_ID_RE = re.compile(r"^[0-9a-f]{32}$")


def new_transaction_id() -> str:
    """A fresh, unguessable transaction id (controller-generated, never agent)."""
    return secrets.token_hex(16)


def render_marker(attestation: ReplanAttestation) -> str:
    """The exact marker a replacement PR body must contain (used in the prompt)."""
    payload = json.dumps(asdict(attestation), sort_keys=True)
    return f"<!-- {MARKER_NAME}: {payload} -->"


def render_close_receipt(transaction_id: str) -> str:
    """The receipt the controller publishes *after* it closes the source PR.

    ``SUPERSEDE_INTENT`` is persisted before ``gh pr close`` runs, so on its
    own it proves an intended write, never a performed one: after a crash in
    that window, a source a human closed and one this transaction closed look
    identical from the journal. The receipt is the missing half. It is posted
    with a separate ``gh pr comment`` only after the controller observed its
    own close landing -- never inside ``gh pr close --comment``, whose comment
    predates the close and could therefore be present even when the close never
    landed. So a source found CLOSED *carrying* the receipt for this
    transaction was closed by this transaction, and one found CLOSED without it
    was closed by somebody else -- which is a refusal, not an adoption.

    This is crash-recovery attribution, not authentication: the transaction id
    is published in the replacement PR body, so a human who wanted to could
    copy it into a comment. It is trusted against crashes and concurrent
    humans, not against a forger.
    """
    return f"<!-- {CLOSE_RECEIPT_NAME}: {transaction_id} -->"


def has_close_receipt(comment_bodies: Iterable[str], transaction_id: str) -> bool:
    """True when some comment carries this transaction's close receipt."""
    if not TRANSACTION_ID_RE.match(transaction_id or ""):
        return False
    return any(
        match.group("txn") == transaction_id
        for body in comment_bodies
        for match in CLOSE_RECEIPT_RE.finditer(body or "")
    )


class ReplanStage(StrEnum):
    """Monotonic transaction stages. ``REJECTED`` is terminal for the run."""

    # Recorded by REVIEW when it routes to REPLAN_REEXECUTE: the decision to
    # replan, before the controller has checkpointed anything. It carries the
    # escalation metadata and no transaction id.
    PENDING = "pending"
    PREPARED = "prepared"
    VERIFIED = "verified"
    SUPERSEDE_INTENT = "supersede_intent"
    # The controller closed the source, then found a checkpoint had moved
    # inside the close window. Persisted *before* `gh pr reopen` so that the
    # decision to undo survives a crash: from here the only outcomes are a
    # confirmed reopen or a block naming the manual step. Never a second close.
    COMPENSATING = "compensating"
    SUPERSEDED = "superseded"
    REJECTED = "rejected"


class Disposition(StrEnum):
    """How conclusive an observation is — the distinction recovery turns on.

    ``UNKNOWN`` (a transient GitHub failure) must stay resumable; only
    ``REJECTED`` and ``AMBIGUOUS`` are terminal, and they are persisted so a
    later resume replays the decision instead of recomputing it.
    """

    OK = "ok"
    NONE = "none"  # no candidate yet; the agent has not (verifiably) produced one
    AMBIGUOUS = "ambiguous"  # more than one candidate claims this transaction
    REJECTED = "rejected"  # conclusively unacceptable


@dataclass(frozen=True)
class ReplanAttestation:
    """The agent's machine-readable claim, published on the replacement PR."""

    transaction_id: str
    execution_attempt: int
    findings_considered: int
    unique_constraints: int
    tests_passed: bool


@dataclass(frozen=True)
class MarkerScan:
    attestations: list[ReplanAttestation]
    malformed: list[str]  # human-readable reasons, one per unusable marker


def _attestation_from_payload(payload: dict) -> ReplanAttestation:
    """Strictly typed marker payload; raises ValueError with a usable reason."""
    txn_id = payload.get("transaction_id")
    if not isinstance(txn_id, str) or not TRANSACTION_ID_RE.match(txn_id):
        raise ValueError("transaction_id must be 32 lowercase hex characters")
    ints: dict[str, int] = {}
    for key in ("execution_attempt", "findings_considered", "unique_constraints"):
        value = payload.get(key)
        if not isinstance(value, int) or isinstance(value, bool) or value < 0:
            raise ValueError(f"{key} must be an integer >= 0")
        ints[key] = value
    tests_passed = payload.get("tests_passed")
    if not isinstance(tests_passed, bool):
        raise ValueError("tests_passed must be a boolean")
    return ReplanAttestation(
        transaction_id=txn_id,
        execution_attempt=ints["execution_attempt"],
        findings_considered=ints["findings_considered"],
        unique_constraints=ints["unique_constraints"],
        tests_passed=tests_passed,
    )


def scan_replan_markers(body: str) -> MarkerScan:
    """Every replan marker in ``body``, split into usable and malformed.

    A malformed marker is reported rather than skipped: a PR body that tries
    to carry an attestation and fails is evidence of a broken agent, not of an
    unrelated PR, and the caller fails closed on it. "Malformed" therefore
    covers every complete marker whose payload is not a usable attestation --
    unparsable text, a JSON scalar or array, and a JSON object with bad
    fields alike.
    """
    attestations: list[ReplanAttestation] = []
    malformed: list[str] = []
    for match in MARKER_RE.finditer(body or ""):
        raw = match.group("payload")
        try:
            payload = json.loads(raw)
        except ValueError as exc:
            malformed.append(f"marker payload is not valid JSON ({exc})")
            continue
        if not isinstance(payload, dict):
            malformed.append("marker payload must be a JSON object")
            continue
        try:
            attestations.append(_attestation_from_payload(payload))
        except ValueError as exc:
            malformed.append(f"marker payload is invalid ({exc})")
    return MarkerScan(attestations, malformed)


@dataclass
class ReplanTransaction:
    """Durable intent for one replan. Persisted as ``state.replan_transaction``.

    The field groups mirror the invariants: a *source* checkpoint (the PR that
    may be closed), a *base* the replacement must be built on, the *evidence*
    the replacement must answer for, the *provenance* that binds a candidate
    to this transaction, the verified *target*, and the record of the
    destructive write.
    """

    transaction_id: str = ""
    stage: ReplanStage = ReplanStage.PENDING

    issue_url: str = ""

    # -- decision point: the review state that routed to this replan -------
    # Recorded by REVIEW when the transaction is created, before the
    # controller looks at GitHub again. The source may only be superseded at
    # exactly this revision: it is the one whose findings justify the replan.
    decision_head_sha: str = ""
    decision_branch: str = ""

    # -- source checkpoint: exactly what may be superseded -----------------
    source_pr_url: str = ""
    source_branch: str = ""
    source_head_sha: str = ""
    source_review_round: int = 0

    # -- base: independently verified default branch ----------------------
    base_branch: str = ""

    # -- evidence the replacement must account for ------------------------
    evidence_finding_count: int = 0
    rendered_findings: str = ""
    rendered_observations: str = ""
    rendered_verification_failures: str = ""

    # -- provenance -------------------------------------------------------
    # Largest PR number in the repository when this transaction was prepared,
    # read *before* the transaction id existed. GitHub allocates PR numbers
    # from a monotonic per-repository counter, so any PR at or below this
    # predates the id and therefore cannot be the replacement -- whether or not
    # it was linked to the issue, named for it, or even open at the time.
    pr_number_watermark: int = 0
    # Defence in depth over the watermark: the issue's open PRs at PREPARED,
    # by identity. None of them can ever be adopted as the replacement.
    preexisting_pr_urls: list[str] = field(default_factory=list)
    expected_execution_attempt: int = 0

    # -- target: the verified replacement ---------------------------------
    replacement_pr_url: str = ""
    replacement_branch: str = ""
    replacement_head_sha: str = ""
    attested_findings_considered: int = 0
    attested_unique_constraints: int = 0

    # -- destructive write ------------------------------------------------
    close_intent_at: str = ""
    superseded_at: str = ""

    # -- compensation -----------------------------------------------------
    # Written together with stage COMPENSATING, before `gh pr reopen` is
    # called. ``compensation_reason`` is the drift that made the close
    # unacceptable; it is replayed verbatim by a resume so the undo cannot be
    # re-derived (and possibly re-decided) from GitHub facts that have since
    # settled back into place.
    compensating_at: str = ""
    compensation_reason: str = ""

    # -- disposition ------------------------------------------------------
    rejection_reason: str = ""
    rejected_pr_url: str = ""

    escalation: dict = field(default_factory=dict)

    # -- persistence ------------------------------------------------------
    def to_dict(self) -> dict:
        data = asdict(self)
        data["stage"] = self.stage.value
        return data

    @classmethod
    def from_dict(cls, data: dict) -> ReplanTransaction:
        """Load persisted intent; unknown/omitted fields fall back to defaults.

        An unreadable stage is *not* coerced to a runnable one — it becomes
        ``REJECTED`` so a hand-edited or future-version journal fails closed
        instead of resuming a destructive write from an unknown position.
        """
        if not isinstance(data, dict):
            raise ValueError("replan transaction must be a JSON object")
        known = {f for f in cls.__dataclass_fields__}
        kwargs = {k: v for k, v in data.items() if k in known}
        raw_stage = kwargs.pop("stage", ReplanStage.PENDING.value)
        try:
            stage = ReplanStage(raw_stage)
        except ValueError:
            stage = ReplanStage.REJECTED
            if not kwargs.get("rejection_reason"):
                kwargs["rejection_reason"] = (
                    f"persisted replan transaction has unknown stage {raw_stage!r}"
                )
        txn = cls(stage=stage, **kwargs)
        return txn

    @property
    def is_bound(self) -> bool:
        return bool(self.replacement_pr_url)

    def marker_example(self) -> str:
        """The literal marker the agent must publish, with real values filled in."""
        return render_marker(
            ReplanAttestation(
                transaction_id=self.transaction_id,
                execution_attempt=self.expected_execution_attempt,
                findings_considered=self.evidence_finding_count,
                unique_constraints=0,
                tests_passed=True,
            )
        )


# ---------------------------------------------------------------------------
# Verification predicates. Each returns "" when the check passes, or a
# human-readable reason why the transaction must not proceed. They are the
# single definition of "acceptable" for the normal path and for `resume`:
# there is exactly one, so the two cannot drift.
# ---------------------------------------------------------------------------


def _canonical(url: str) -> str:
    try:
        return parse_pr_url(url).canonical
    except Exception:
        return ""


def verify_decision_point(pr: PRInfo, txn: ReplanTransaction) -> str:
    """The source must still be the revision whose review decided the replan.

    Checked once, before the transaction is prepared. ``REVIEW`` records the
    HEAD and branch it reviewed; the checkpoint is then taken from GitHub, and
    between those two moments a human (or a stray push) can move the source.
    Superseding the moved source would close a revision this replan decision
    never saw -- the accumulated findings belong to the reviewed revision, not
    to whatever is on the branch now.

    An empty ``decision_head_sha`` is itself a refusal: without it there is no
    proof the checkpoint is the decision point.
    """
    if not txn.decision_head_sha:
        return (
            "the replan transaction does not record the reviewed HEAD that decided it, so the "
            "source cannot be proven to be the revision the findings belong to"
        )
    if pr.head_sha.lower() != txn.decision_head_sha.lower():
        return (
            f"source PR {txn.source_pr_url} is at HEAD {pr.head_sha or '(unreadable)'}, but the "
            f"review that decided this replan ran on {txn.decision_head_sha}; the current work "
            "was never reviewed against this decision"
        )
    if txn.decision_branch and pr.head_ref != txn.decision_branch:
        return (
            f"source PR {txn.source_pr_url} is on branch {pr.head_ref!r}, but the review that "
            f"decided this replan ran on {txn.decision_branch!r}"
        )
    return ""


def verify_source_checkpoint(pr: PRInfo, txn: ReplanTransaction) -> str:
    """The source PR must still be *exactly* what the transaction checkpointed.

    Closing a PR is irreversible for the review evidence it carries, so this
    is the compare half of a compare-and-swap: identity, OPEN state, branch,
    and the exact checkpointed HEAD. Any drift — including a push that landed
    after the checkpoint, and a close performed by someone else — means the
    controller is no longer looking at the implementation it decided to
    replace, and must not close it.
    """
    if _canonical(pr.url) != _canonical(txn.source_pr_url):
        return (
            f"source PR identity mismatch: read {pr.url or '(none)'}, "
            f"checkpoint {txn.source_pr_url}"
        )
    if pr.state == "MERGED":
        return f"source PR {txn.source_pr_url} is already MERGED; refusing to supersede it"
    if not pr.is_open:
        return (
            f"source PR {txn.source_pr_url} is {pr.state or '(unknown)'}, expected OPEN at the "
            "checkpoint; it was not closed by this transaction"
        )
    if txn.source_branch and pr.head_ref != txn.source_branch:
        return (
            f"source PR {txn.source_pr_url} moved from the checkpointed branch "
            f"{txn.source_branch!r} to {pr.head_ref!r}"
        )
    if pr.head_sha != txn.source_head_sha:
        return (
            f"source PR {txn.source_pr_url} advanced from the checkpointed HEAD "
            f"{txn.source_head_sha} to {pr.head_sha or '(unreadable)'}; the newer work was never "
            "reviewed against this replan decision"
        )
    # Defence in depth: the checkpoint is only allowed to hold the revision the
    # review decided on, so a journal in which the two disagree is unusable.
    if txn.decision_head_sha and txn.source_head_sha.lower() != txn.decision_head_sha.lower():
        return (
            f"checkpointed source HEAD {txn.source_head_sha} is not the reviewed HEAD "
            f"{txn.decision_head_sha} that decided this replan"
        )
    return ""


def verify_target_pr(
    pr: PRInfo,
    txn: ReplanTransaction,
    repository: str,
    *,
    require_checkpoint_head: bool,
) -> str:
    """Objective facts a replacement must satisfy, re-derived from GitHub.

    ``require_checkpoint_head`` is off while the candidate is first being
    bound (its HEAD *becomes* the checkpoint) and on for every later read,
    including the final read immediately before the destructive write.
    """
    ref_canonical = _canonical(pr.url)
    if not ref_canonical:
        return f"replacement PR URL {pr.url!r} is not a pull-request URL"
    if ref_canonical == _canonical(txn.source_pr_url):
        return "replacement PR must differ from the superseded PR"
    if txn.replacement_pr_url and ref_canonical != _canonical(txn.replacement_pr_url):
        return (
            f"replacement PR identity mismatch: read {ref_canonical}, "
            f"checkpoint {txn.replacement_pr_url}"
        )
    pr_repo = parse_pr_url(ref_canonical).repository
    if pr_repo.lower() != repository.lower() or (
        pr.repository and pr.repository.lower() != repository.lower()
    ):
        return f"replacement PR {ref_canonical} is not in {repository}"
    if not pr.is_open:
        return f"replacement PR {ref_canonical} is {pr.state or '(unknown)'}, expected OPEN"
    if not pr.head_sha:
        return f"replacement PR {ref_canonical} has no readable head SHA"
    if not pr.head_ref or pr.head_ref == txn.source_branch:
        return "replacement branch must be present and differ from the superseded branch"
    if txn.replacement_branch and pr.head_ref != txn.replacement_branch:
        return (
            f"replacement PR {ref_canonical} moved from the checkpointed branch "
            f"{txn.replacement_branch!r} to {pr.head_ref!r}"
        )
    if pr.base_ref != txn.base_branch:
        return (
            f"replacement PR base {pr.base_ref!r} != verified default branch {txn.base_branch!r}"
        )
    issue_number = parse_issue_url(txn.issue_url).number
    if issue_number not in pr.linked_issue_numbers:
        return f"replacement PR {ref_canonical} is not linked to issue #{issue_number}"
    if require_checkpoint_head and pr.head_sha != txn.replacement_head_sha:
        return (
            f"replacement PR {ref_canonical} advanced from the verified HEAD "
            f"{txn.replacement_head_sha} to {pr.head_sha}; it is no longer the implementation "
            "the controller verified"
        )
    return ""


def verify_attestation(attestation: ReplanAttestation, txn: ReplanTransaction) -> str:
    """The agent's published claim must satisfy the controller's requirements.

    ``findings_considered`` is the acknowledgement invariant: the replacement
    lifecycle may only supersede the source once the agent has stated it
    accounted for every actionable finding the controller preserved. The
    controller never lowers that requirement — a transaction is only prepared
    when the evidence is provably complete.
    """
    if attestation.transaction_id != txn.transaction_id:
        return (
            f"attestation belongs to transaction {attestation.transaction_id!r}, "
            f"not {txn.transaction_id!r}"
        )
    if attestation.execution_attempt != txn.expected_execution_attempt:
        return (
            f"attested execution_attempt {attestation.execution_attempt} != "
            f"{txn.expected_execution_attempt} expected by the controller"
        )
    if not attestation.tests_passed:
        return "the replacement attests tests_passed=false"
    if attestation.findings_considered < txn.evidence_finding_count:
        return (
            f"the replacement attests it considered {attestation.findings_considered} of the "
            f"{txn.evidence_finding_count} historical finding(s) the controller preserved"
        )
    if attestation.unique_constraints > attestation.findings_considered:
        return (
            f"attested unique_constraints {attestation.unique_constraints} exceeds "
            f"findings_considered {attestation.findings_considered}"
        )
    return ""


def verify_closed_source(pr: PRInfo, txn: ReplanTransaction) -> str:
    """The source, re-read *after* the controller's close, is still the one it closed.

    ``gh pr close`` carries no precondition, so the swap half of the
    compare-and-swap is completed here instead: everything the pre-close read
    established must still be true of the PR that is now closed, except the
    state itself. A HEAD or branch that moved means a push landed inside the
    write window, i.e. the close destroyed the visibility of work that no
    review ever saw -- the caller undoes the close rather than accepting it.
    """
    if _canonical(pr.url) != _canonical(txn.source_pr_url):
        return (
            f"source PR identity mismatch after the close: read {pr.url or '(none)'}, "
            f"checkpoint {txn.source_pr_url}"
        )
    if pr.state != "CLOSED":
        return (
            f"source PR {txn.source_pr_url} is {pr.state or '(unknown)'} after this "
            "transaction's close attempt; expected CLOSED"
        )
    if txn.source_branch and pr.head_ref != txn.source_branch:
        return (
            f"source PR {txn.source_pr_url} moved from the checkpointed branch "
            f"{txn.source_branch!r} to {pr.head_ref!r} inside the close window"
        )
    if pr.head_sha != txn.source_head_sha:
        return (
            f"source PR {txn.source_pr_url} advanced from the checkpointed HEAD "
            f"{txn.source_head_sha} to {pr.head_sha or '(unreadable)'} inside the close window; "
            "the newer work was never reviewed against this replan decision"
        )
    return ""


def verify_target_marker(pr: PRInfo, txn: ReplanTransaction) -> str:
    """The replacement's body still *proves* it is this transaction's replacement.

    :func:`verify_target_pr` re-derives the objective facts (identity, state,
    branch, base, linkage, HEAD); none of them is provenance. The marker is,
    and a body can be edited after the controller verified it: dropping the
    marker, or restating the attestation with different numbers, leaves every
    objective fact valid while removing the only evidence that this PR belongs
    to this replan. So the body is re-scanned on the final read, under exactly
    the rules that bound it in the first place -- one usable marker for this
    transaction, nothing marker-shaped beside it -- plus equality with the
    attestation the controller checkpointed at ``VERIFIED``.
    """
    scan = scan_replan_markers(pr.body or "")
    ref = _canonical(pr.url) or pr.url or "(none)"
    if scan.malformed:
        return (
            f"replacement PR {ref} carries an unusable replan marker "
            f"({'; '.join(scan.malformed)})"
        )
    mine = [a for a in scan.attestations if a.transaction_id == txn.transaction_id]
    if not mine:
        return (
            f"replacement PR {ref} no longer carries the marker for replan transaction "
            f"{txn.transaction_id}, so it can no longer be proven to be its replacement"
        )
    if len(mine) > 1:
        return f"replacement PR {ref} carries {len(mine)} markers for this transaction"
    drift = verify_attestation(mine[0], txn)
    if drift:
        return drift
    attestation = mine[0]
    if (
        attestation.findings_considered != txn.attested_findings_considered
        or attestation.unique_constraints != txn.attested_unique_constraints
    ):
        return (
            f"replacement PR {ref} now attests findings_considered="
            f"{attestation.findings_considered}/unique_constraints="
            f"{attestation.unique_constraints}, but the controller verified "
            f"{txn.attested_findings_considered}/{txn.attested_unique_constraints}"
        )
    return ""


@dataclass(frozen=True)
class CandidateSelection:
    """The result of looking for this transaction's replacement on GitHub."""

    disposition: Disposition
    pr: PRInfo | None = None
    attestation: ReplanAttestation | None = None
    reason: str = ""


def select_bound_candidate(open_prs: list[PRInfo], txn: ReplanTransaction) -> CandidateSelection:
    """Find the one PR causally bound to ``txn``, or fail closed.

    ``open_prs`` must be *every* open PR in the repository, not the subset
    that already looks related to the issue: an agent creates the PR and links
    it to the issue in separate operations, so a crash between the two leaves
    a marked replacement that no issue-shaped filter can see. Missing it would
    report "no candidate" and start a second implementation attempt — the one
    outcome crash idempotency forbids. Found here, it is judged on its merits
    instead: :func:`verify_target_pr` refuses it for the missing linkage, and
    the phase blocks for a human with the PR named.

    Binding is positive proof, never shape: a candidate must carry a marker
    for this exact transaction id, and must have been *created* after that id
    existed. Everything else is ignored, so an unrelated open PR neither gets
    adopted nor blocks a healthy replan. Two bound candidates are ambiguous,
    and a candidate whose marker is unusable in any way -- malformed, doubled,
    or sitting on a PR that predates the transaction -- is a conclusive
    rejection.

    Novelty is decided by ``pr_number_watermark`` rather than by the snapshot
    of issue PRs: GitHub numbers PRs from a monotonic per-repository counter,
    so "number <= watermark" covers every PR that already existed, including
    ones that were closed, unlinked, or named nothing like this issue at
    ``PREPARED`` and were only linked to it afterwards.
    """
    if not TRANSACTION_ID_RE.match(txn.transaction_id):
        # No id means nothing can be causally bound to this transaction; a
        # marker matching "" would otherwise adopt an arbitrary PR.
        return CandidateSelection(
            Disposition.REJECTED,
            reason=(
                "replan transaction has no usable transaction id; no PR can be proven to be "
                "its replacement"
            ),
        )
    if txn.pr_number_watermark < 1:
        # Without the watermark there is no proof any candidate postdates the
        # transaction id, and provenance would fall back to shape.
        return CandidateSelection(
            Disposition.REJECTED,
            reason=(
                f"replan transaction {txn.transaction_id} has no pull-request number watermark, "
                "so no PR can be proven to have been created after it"
            ),
        )
    preexisting = {_canonical(url) for url in txn.preexisting_pr_urls}
    source = _canonical(txn.source_pr_url)
    bound: list[tuple[PRInfo, ReplanAttestation]] = []
    malformed: list[str] = []
    for pr in open_prs:
        canonical = _canonical(pr.url)
        if not canonical or canonical == source:
            continue
        scan = scan_replan_markers(pr.body or "")
        mine = [a for a in scan.attestations if a.transaction_id == txn.transaction_id]
        under_watermark = pr.number <= txn.pr_number_watermark
        if under_watermark or canonical in preexisting:
            if mine:
                # The id did not exist when this PR was created, so a match
                # means the marker was copied. Never adopt it.
                how = (
                    f"its number {pr.number} is at or below the watermark {txn.pr_number_watermark}"
                    if under_watermark
                    else "it was in the snapshot of the issue's open PRs"
                )
                return CandidateSelection(
                    Disposition.REJECTED,
                    reason=(
                        f"PR {canonical} already existed when replan transaction "
                        f"{txn.transaction_id} was prepared ({how}) but carries its marker; "
                        "refusing to adopt a pre-existing PR as a replacement"
                    ),
                )
            continue
        if len(mine) > 1:
            return CandidateSelection(
                Disposition.REJECTED,
                reason=f"PR {canonical} carries {len(mine)} markers for this transaction",
            )
        if mine and scan.malformed:
            # A valid marker does not excuse an unusable one beside it: the
            # body was supposed to carry exactly one attestation, and a
            # candidate whose provenance data is partly garbage fails closed.
            return CandidateSelection(
                Disposition.REJECTED,
                reason=(
                    f"PR {canonical} carries the marker for replan transaction "
                    f"{txn.transaction_id} alongside an unusable one "
                    f"({'; '.join(scan.malformed)})"
                ),
            )
        if scan.malformed:
            malformed.append(f"{canonical}: {'; '.join(scan.malformed)}")
        if mine:
            bound.append((pr, mine[0]))
    if len(bound) > 1:
        urls = ", ".join(sorted(_canonical(pr.url) for pr, _ in bound))
        return CandidateSelection(
            Disposition.AMBIGUOUS,
            reason=(
                f"{len(bound)} open PRs claim replan transaction {txn.transaction_id}: {urls}. "
                "The controller cannot tell which one is the replacement"
            ),
        )
    if bound:
        pr, attestation = bound[0]
        return CandidateSelection(Disposition.OK, pr=pr, attestation=attestation)
    if malformed:
        return CandidateSelection(
            Disposition.REJECTED,
            reason="unusable replan marker on " + "; ".join(malformed),
        )
    return CandidateSelection(Disposition.NONE)


def find_non_open_claimant(
    all_prs: list[PRInfo], txn: ReplanTransaction
) -> CandidateSelection:
    """A marker-bearing non-open PR for ``txn``, or NONE when there is none.

    ``select_bound_candidate`` only sees open PRs. A replacement the first
    agent created and that was then closed (by a human, or by the agent
    itself) is invisible there, and reporting "no candidate" would invoke the
    agent a second time -- the one outcome crash idempotency forbids. This
    scans the exhaustive repository-wide set (open, closed and merged alike)
    for a PR carrying this transaction's marker that is not open, and turns
    it into a durable rejection naming the PR, never into absence.

    Pre-existing non-open PRs carrying a copied marker are reported as
    pre-existing, exactly as the open path does; post-watermark ones are
    reported with their observed state (CLOSED/MERGED), because they prove a
    first implementation attempt already happened.
    """
    if not TRANSACTION_ID_RE.match(txn.transaction_id):
        return CandidateSelection(Disposition.NONE)
    if txn.pr_number_watermark < 1:
        return CandidateSelection(Disposition.NONE)
    preexisting = {_canonical(url) for url in txn.preexisting_pr_urls}
    source = _canonical(txn.source_pr_url)
    for pr in all_prs:
        if pr.is_open:
            continue
        canonical = _canonical(pr.url)
        if not canonical or canonical == source:
            continue
        scan = scan_replan_markers(pr.body or "")
        mine = [a for a in scan.attestations if a.transaction_id == txn.transaction_id]
        if not mine:
            continue
        under_watermark = pr.number <= txn.pr_number_watermark
        if under_watermark or canonical in preexisting:
            how = (
                f"its number {pr.number} is at or below the watermark {txn.pr_number_watermark}"
                if under_watermark
                else "it was in the snapshot of the issue's open PRs"
            )
            return CandidateSelection(
                Disposition.REJECTED,
                reason=(
                    f"PR {canonical} already existed when replan transaction "
                    f"{txn.transaction_id} was prepared ({how}) but carries its marker; "
                    "refusing to adopt a pre-existing PR as a replacement"
                ),
            )
        return CandidateSelection(
            Disposition.REJECTED,
            reason=(
                f"PR {canonical} carries the marker for replan transaction "
                f"{txn.transaction_id} but is {pr.state or '(unknown)'}, expected OPEN; "
                "a first replacement attempt already exists and must be decided by a human, "
                "not by invoking the agent again"
            ),
        )
    return CandidateSelection(Disposition.NONE)
